---
title: "5ad"
output: html_document
---

## Cinetic graphics during simulation

```{r, echo=TRUE}
library(cowplot)
library(tidyverse)
```

```{r, echo=TRUE}
specialRead <- function(x) {
  read_csv(file=x, col_names = TRUE, col_types= "nnnnnnnnnn")
}

concatFiles <- function (base, folder){
   fullPath = paste(base,folder,sep="")
   list.files(path = fullPath, full.names = TRUE, pattern = "(\\d_\\d_\\d)") %>% lapply(specialRead) %>% bind_rows
}
```

### Higher Prop

```{r, fig.width=20}
base <- "/home/reyman/Data/5ad/mars2022"

sortie_sc5_higherprop <- concatFiles(base,"/statistics/HigherProp")
sortie_sc5_higherprop$propHealthy <- sortie_sc5_higherprop$healthy / sortie_sc5_higherprop$effective 
  
sortieLong_sc5_hp <- gather(sortie_sc5_higherprop, facteur, valeur,c(propHealthy,avgOpinion) ) 
sortieLong_sc5_hp <- mutate(sortieLong_sc5_hp, "ds" = gsub(" ", "", paste(paste("[",paste(sortieLong_sc5_hp$day, sortieLong_sc5_hp$slice)),"]")))

p <- ggplot(data=sortieLong_sc5_hp, aes(x=ds, y=valeur, group=educ, fill=educ, colour=as.character(educ)))
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p <- p + geom_line(size=0.5) + facet_grid(facteur ~ sex ~ age, labeller = label_both,scales = "free_y") #show.legend = FALSE
p
ggsave("sc_higherprop.pdf")
```

### SmallerProp

## Other observable 

### Prepare data

```{r, fig.width=20}
base <- "/home/reyman/Data/5ad/mars2022"

 recode <- function(x) {
  step_to_day <- c (
  '00' = 'day 0 step 1',
  '01' = 'day 0 step 2',
  '02' = 'day 0 step 3',
  '10' = 'day 1 step 1',
  '11' = 'day 1 step 2',
  '12' = 'day 1 step 3',
  '20' = 'day 2 step 1',
  '21' = 'day 2 step 2',
  '22' = 'day 2 step 3',
  '30' = 'day 3 step 1',
  '31' = 'day 3 step 2',
  '32' = 'day 3 step 3',
  '40' = 'day 4 step 1',
  '41' = 'day 4 step 2',
  '42' = 'day 4 step 3',
  '50' = 'day 5 step 1',
  '51' = 'day 5 step 2',
  '52' = 'day 5 step 3'
  )
  return(step_to_day[x])
}

hp_sc5_health <- read_csv(paste0(base,"/statistics/HigherProp/health.csv"))
hp_sc5_health$propHealthy <- hp_sc5_health$healthy / hp_sc5_health$effective 
 
hpLong_sc5_health <- hp_sc5_health %>%
  gather(key=facteur, value=valeur, propHealthy,avgOpinion,socialInequality,e ) %>%
  mutate(ds= recode(paste0(day, slice)))
 
sp_sc5_health <- read_csv(paste0(base,"/statistics/SmallerProp/health.csv"))
sp_sc5_health$propHealthy <- sp_sc5_health$healthy / sp_sc5_health$effective 

spLong_sc5_health <- sp_sc5_health %>%
  gather(key=facteur, value=valeur, propHealthy,avgOpinion,socialInequality,e ) %>%
  mutate(ds= recode(paste0(day, slice)))

hpLong_sc5_health <-  hpLong_sc5_health %>% mutate (type="hp")
spLong_sc5_health <- spLong_sc5_health %>% mutate (type="sp")


both_sc5_health <- rbind(hpLong_sc5_health, spLong_sc5_health) %>% mutate(type = as.factor(type))
```

### Higher Prop

Multiple graphics using cowplots 

```{r, fig.width=70}

p_hp_propHealthy <- both_sc5_health %>% filter(facteur=="propHealthy")  %>% ggplot( aes(x=ds, y=valeur,colour=type) )+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1.0)) +
  theme(axis.text.x.bottom = element_text(margin=margin(t=0, r=0,b=10,l=0)) ) +
  geom_point()   +
  labs(y= "Value", x = "prop. of Healthy")

p_hp_propHealthy
#ggsave("p_hp_propHealthy.pdf")

p_hp_ineq <- both_sc5_health %>% filter(facteur=="socialInequality")  %>% ggplot( aes(x=ds, y=valeur,colour=type)) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1.0)) +
  theme(axis.text.x.bottom = element_text(margin=margin(t=0, r=0,b=10,l=0)) ) +
  geom_point()   +
  labs(y= "Value", x = "Social Inequality")

p_hp_ineq
#ggsave("p_hp_ineq.pdf")


p_hp_e <- both_sc5_health %>% filter(facteur=="e")  %>% ggplot( aes(x=ds, y=valeur,colour=type)) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1.0)) +
  theme(axis.text.x.bottom = element_text(margin=margin(t=0, r=0,b=10,l=0)) ) +
  geom_point()   +
  labs(y= "Value", x = "Guido")

p_hp_e
#ggsave("p_hp_e.pdf")

c <- plot_grid(p_hp_propHealthy, p_hp_ineq,p_hp_e, labels = "AUTO",nrow=1, align="h")
ggsave("c.pdf",c, width=20)
```

```{r, fig.width=20}
base <- "/home/reyman/TRASH/5ad/mars2022"

sortie_sc5_smallerProp <- concatFiles(base,"/statistics/SmallerProp")
sortie_sc5_smallerProp$propHealthy <- sortie_sc5_smallerProp$healthy / sortie_sc5_smallerProp$effective 
  
sortieLong_sc5_sp <- gather(sortie_sc5_smallerProp, facteur, valeur,c(propHealthy,avgOpinion) ) 
sortieLong_sc5_sp <- mutate(sortieLong_sc5_sp, "ds" = gsub(" ", "", paste(paste("[",paste(sortieLong_sc5_sp$day, sortieLong_sc5_sp$slice)),"]")))

p <- ggplot(data=sortieLong_sc5_sp, aes(x=ds, y=valeur, group=educ, fill=educ, colour=as.character(educ)))
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p <- p + geom_line(size=0.5) + facet_grid(facteur ~ sex ~ age, labeller = label_both,scales = "free_y") #show.legend = FALSE
p
ggsave("sc_smallerprop.pdf")

```

## Valentine

'(/[.*?/])')

```{r echo=TRUE}

base <- "/home/reyman/TRASH/5ad/mai2021"
path_valentine <- file.path(base,"locdata_movdata_2021-05-19.csv")
path_right <- file.path(base,"rightMay.csv")
path_left <- file.path(base,"leftMay.csv")

## Valentine
v_val <- read.table(path_valentine, sep = ",",header = TRUE)
v_val$id <- seq.int(nrow(v_val))

v_val_selected <- v_val %>% 
  mutate(clean_noH = str_replace_all(v_val$numberOfHealthy, "[\\[\\]]", "")) %>%
  mutate(clean_oM = str_replace_all(v_val$opinionMedian, "[\\[\\]]", "")) %>%
  mutate(clean_sI = str_replace_all(v_val$socialInequality, "[\\[\\]]", "")) %>%
  select(-numberOfHealthy, -opinionMedian, -socialInequality) %>% 
  separate_rows(c(clean_noH,clean_sI,clean_oM), sep = ',', convert = TRUE ) %>%  
  group_by(id) %>%
  mutate(step=row_number()) %>%
  gather(param,value,clean_noH,clean_oM,clean_sI) %>%
  mutate(exp="valentine")

## Left
v_left <- read.table(path_left, sep = ",",header = TRUE)
v_left$id <- seq.int(nrow(v_left))

v_left_selected <- v_left %>% 
  mutate(clean_noH = str_replace_all(v_left$numberOfHealthy, "[\\[\\]]", "")) %>%
  mutate(clean_oM = str_replace_all(v_left$opinionMedian, "[\\[\\]]", "")) %>%
  mutate(clean_sI = str_replace_all(v_left$socialInequality, "[\\[\\]]", "")) %>%
  select(-numberOfHealthy, -opinionMedian, -socialInequality) %>% 
  separate_rows(c(clean_noH,clean_sI,clean_oM), sep = ',', convert = TRUE ) %>%  
  group_by(id) %>%
  mutate(step=row_number()) %>%
  gather(param,value,clean_noH,clean_oM,clean_sI) %>%
  mutate(exp="left") 

## Right
v_right <- read.table(path_right, sep = ",",header = TRUE)
v_right$id <- seq.int(nrow(v_right))

v_right_selected <- v_right %>% 
  mutate(clean_noH = str_replace_all(v_right$numberOfHealthy, "[\\[\\]]", "")) %>%
  mutate(clean_oM = str_replace_all(v_right$opinionMedian, "[\\[\\]]", "")) %>%
  mutate(clean_sI = str_replace_all(v_right$socialInequality, "[\\[\\]]", "")) %>%
  select(-numberOfHealthy, -opinionMedian, -socialInequality) %>% 
  separate_rows(c(clean_noH,clean_sI,clean_oM), sep = ',', convert = TRUE ) %>%  
  group_by(id) %>%
  mutate(step=row_number()) %>%
  gather(param,value,clean_noH,clean_oM,clean_sI) %>%
  mutate(exp="right")


exp <- bind_rows(v_val_selected, v_right_selected, v_left_selected)

p <- ggplot(data=exp, aes(x=step, y=value, group = interaction(exp,param,id), color = exp))
p <- p + geom_line(alpha = 0.05) + facet_wrap( ~ param , labeller = label_both,scales = "free") 
p

ggsave("one_with_all.pdf",device = cairo_pdf, width=297, height = 210,units = "mm")


p <- ggplot(data=exp, aes(x=step, y=value, group = interaction(exp,param,id), color = exp))
p <- p + geom_line(alpha = 0.05) + facet_wrap( exp ~ param , labeller = label_both,scales = "free") 
p

ggsave("multiple_with_all.pdf",device = cairo_pdf, width=297, height = 210,units = "mm")
```


```{r echo=TRUE}

sim <- read.csv2("results-25042022-10000replications.csv", sep=",", dec=".")
sim$Scenario <- ifelse(sim$numOfScenario == 1, "1A: Random residence / no move",
                       ifelse(sim$numOfScenario == 2, "1B: Random residence / random moves",
                              ifelse(sim$numOfScenario == 3, "2A: Observed residence / no move",
                                     ifelse(sim$numOfScenario == 4, "2B: Observed residence / random moves",
                                            "2C: Observed residence / observed moves"))))

# mean_1A <- mean(sim[sim$numOfScenario == 1,"socialInequality"])
# mean_1B <- mean(sim[sim$numOfScenario == 2,"socialInequality"])
# mean_2A <- mean(sim[sim$numOfScenario == 3,"socialInequality"])
# mean_2B <- mean(sim[sim$numOfScenario == 4,"socialInequality"])
# mean_2C <- mean(sim[sim$numOfScenario == 5,"socialInequality"])

sim %>%
  ggplot( aes(x=socialInequality, group=Scenario, fill=Scenario)) +
  geom_density(alpha=0.6) +
  scale_fill_manual(values=c("firebrick2", "mediumorchid4", "dodgerblue2", "darkorange2", "springgreen3"))+
  theme_bw() +
  # geom_vline(xintercept=mean_1A, size=0.4, color="firebrick2") + 
  # geom_vline(xintercept=mean_1B, size=0.4, color="mediumorchid4") +
  # geom_vline(xintercept=mean_2A, size=0.4, color="dodgerblue2") +
  # geom_vline(xintercept=mean_2B, size=0.4, color="darkorange2") +
  # geom_vline(xintercept=mean_2C, size=0.4, color="springgreen3") +
  # annotate("text", x=mean_1A + 0.004, y= -10, size=2.5, label=round(mean_1A,3), color="firebrick2") +
  # annotate("text", x=mean_1B + 0.004 , y= -10, size=2.5, label=round(mean_1B,3), color="mediumorchid4") +
  # annotate("text", x=mean_2A + 0.004 , y= -10, size=2.5, label=round(mean_2A,3), color="dodgerblue2") +
  # annotate("text", x=mean_2B + 0.004 , y= -10, size=2.5, label=round(mean_2B,3), color="darkorange2") +
  # annotate("text", x=mean_2C + 0.004, y= -10, size=2, label=round(mean_2C,3), color="springgreen3") +
   xlab("Social Inequality Index") +
  ylab("Density of simulations") + 
  guides(fill=guide_legend(title="Type of scenario")) #+ 

```
 


