name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout h24
      uses: actions/checkout@v2
      with:
        repository: eighties-cities/h24
        path: h24
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: publish h24
      run: sbt publishLocal
    - name: checkout 5aday
      uses: actions/checkout@v2
      with:
        path: main
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: compile 5aday
      run: sbt osgiBundle
