name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout h24
      uses: actions/checkout@v2
      with:
        repository: eighties-cities/h24
        path: h24
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: publish h24
      run: |
           cd h24
           source getData.sh
           sbt publishLocal
           unzip InputODData/H24_location_noID_ParisRegion.zip -d prepared_data_IDF/
           lzma -f prepared_data_IDF/H24_location_noID_ParisRegion.csv
           sbt "runMain eighties.h24.tools.ExtractRelevantData -c data/CONTOURS-IRIS_2-0__SHP_LAMB93_FXX_2014-01-01/CONTOURS-IRIS/1_DONNEES_LIVRAISON_2014/CONTOURS-IRIS_2-0_SHP_LAMB93_FE-2014/CONTOURS-IRIS_FE.shp -g data/GRID/R_rfl09_LAEA1000.shp -p data/base-ic-evol-struct-pop-2012.xls -f data/base-ic-diplomes-formation-2012.xls -d 75,77,78,91,92,93,94,95 -o prepared_data_IDF"
           sbt -J-Xmx4G "runMain eighties.h24.tools.PopulationGenerator -c prepared_data_IDF/CONTOURS-IRIS_FE.shp -g prepared_data_IDF/R_rfl09_LAEA1000.shp -s 1000 -p prepared_data_IDF/base-ic-evol-struct-pop-2012.csv.lzma -f prepared_data_IDF/base-ic-diplomes-formation-2012.csv.lzma -o results_IDF/population.bin"
           sbt -J-Xmx4G "runMain eighties.h24.tools.MoveMatrixGenerator -e prepared_data_IDF/H24_location_noID_ParisRegion.csv.lzma -s EPSG:27572 -p results_IDF/population.bin -m results_IDF/moves.bin"
    - name: checkout 5aday
      uses: actions/checkout@v2
      with:
        path: 5ad
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: compile & run 1 simulation of 5aday
      run: |
           cd 5ad
           sbt osgiBundle
           sbt -J-Xmx2G "runMain eighties.fiveaday.run.SimulationApp -d ./data/initialisation_distribution_per_cat_2002_2008.csv -p ../h24/results_IDF/population.bin -m ../h24/results_IDF/moves.bin"
